### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Stelluuh** [learn-co-curriculum/phase-1-quiz-algorithmic-problem-solving#1]
It would have been nice knowing that I had made a typo:

question two: I wrote Bit O Notation instead of Big O Notation and didn't realize. Usually at the end of the quiz it will tell you which questions you got wrong. Unlike the rest of the quizzes i've taken, this one wouldn't tell me which. 

Made multiple attempts to the quiz thinking that it was Question 4 that I kept getting me the wrong answer. First attempt, answer 4 was correct.

**Comment by lizbur10** [comment]
Hi @Stelluuh ! Thank you for bringing this to our attention. It looks as thought one of the settings for this quiz was wrong. It has now been corrected. Apologies for the inconvenience.

Thanks for contributing to the Flatiron School curriculum 💙
